:imagesdir: images

= Karty (Visiona)

Miniaplikacja *Karty* zapewnia dostęp do listy kart (debetowych, kredytowych), do których Użytkownik jest uprawniony.

System Asseco EBP zapewnia Użytkownikowi dostęp do miniaplikacji *Karty* z dwóch głównych poziomów:

* widżetu *Karty* (wyświetlanego na pulpicie o ile Użytkownik nie usunął go z pulpitu),

Widżet karty kredytowej

Widżet karty debetowej

* menu bocznego po wybraniu opcji _Karty_.

W każdym z poziomów miniaplikacji dla Użytkownika dostępne są formatki do obsługi poszczególnych opcji biznesowych opisanych w poniższych podrozdziałach.

Użytkownik posiadający dostęp do miniaplikacji *Karty* ma możliwość:

* przeglądania listy swoich kart lub wszystkich kart danego rachunku,
* przeglądania informacji szczegółowych na temat karty,
* modyfikacji nazwy własnej karty,

NOTE: Funkcjonalność kart dostępna jest dla Użytkownika, który posiada odpowiednie uprawnienia do funkcjonalności. Uprawnienia nadawane są przez Administratora w opcji _Ustawienia → Uprawnienia Użytkowników_.

== Widżet karty

Widżet *Karty* może być w dwóch rozmiarach: standardowym i rozszerzonym.

* ikona – powoduje rozszerzenie widżetu o dodatkowe informacje,
* ikona – powoduje powrót do rozmiaru standardowego.

Na widżecie standardowym możliwe jest:

* wybranie karty w celu zaprezentowania skróconych informacji o niej, czyli:

** *Nazwa i numer* – nazwa karty (nadana przez system), numer karty częściowo zamaskowany (widoczne 4 pierwsze i 4 ostatnie cyfry numeru karty), obok nazwy karty dostępny jest przycisk umożliwiający rozwinięcie listy z dostępnymi kartami.

** *Dostępne środki* – kwota dostępnych środków wraz z walutą,
** *Właściciel* – dane właściciela karty,
** *Data ważności* – data ważności karty (w formacie MM/RRRR),
** *Rodzaj karty* – _Kredytowa , Debetowa, Obciążeniowa_,
** *Limit kredytu* – kwota limitu wraz z walutą.

* uruchomienie następujących akcji:

** [SPŁAĆ KARTĘ] – akcja dostępna tylko dla kart kredytowych, umożliwia spłatę karty kredytowej,
** [SZCZEGÓŁY] – umożliwia przejście do szczegółów wybranej karty.

Na widżecie rozszerzonym oprócz tych samych informacji co na widoku standardowym dodatkowo prezentowane są:

* Ostatnia transakcja – informacja o ostatniej transakcji na karcie:
** *Kwota* – kwota transakcji wraz z walutą,
** *Tytuł* – tytuł transakcji,
** *Data* – data transakcji (data w formacie DD.MM.RRRR).

Widżet rozszerzony karty kredytowej

Widżet rozszerzony karty debetowej

== Przeglądanie listy kart

Po kliknięciu w tytuł widżetu *Karty* lub poprzez wybór opcji z bocznego menu _Karty_ wyświetlane jest okno prezentujące listę kart, do których Użytkownik jest uprawniony:

Na liście kart, dla każdej karty dostępne są następujące informacje:

* *Nazwa i numer* – nazwa karty (nadana przez system), numer karty częściowo zamaskowany (widoczne 4 pierwsze i 4 ostatnie cyfry numeru karty),
* *Rodzaj* – rodzaj karty Kredytowa, Debetowa, Obciążeniowa (z określeniem główna/dodatkowa),
* *Posiadacz* – imię i nazwisko właściciela karty,

** daty zastrzeżenia – jeśli data zastrzeżenia jest przed datą aktualną, wówczas prezentowany jest status _Zastrzeżona_,
** daty zablokowania – jeśli data zablokowania jest przed datą aktualną, wówczas prezentowany jest status _Zablokowana_,
** daty ważności – jeśli data końca ważności jest przed datą aktualną, wówczas prezentowany jest status _Nieważna_.

System umożliwia także filtrowanie listy kart, za pomocą:

* *Filtra prostego* – filtrowanie listy kart następuje po wpisaniu danych w polu wyszukiwania znajdującego się nad listą:

System filtruje listę już po wpisaniu pierwszej litery/cyfry/znaku.

Aby powrócić do pełnej listy rachunków należy kliknąć w ikonę  w polu wyszukiwania.

* *Pola Status* – umożliwia filtrowanie kart po statusie karty poprzez wybór wartości z dostępnej listy:

** Wszystkie,
** _Ważna_ (wartość domyślna) ,
** _Zablokowana,_
** _Zastrzeżona,_
** _Do aktywacji._

W górnej części formularza KARTY dostępny jest przycisk:

* – umożliwiający wyjście do pulpitu.

== Akcje na wybranej karcie

Kliknięcie w wiersz wybranej karty powoduje wyświetlenie dodatkowych informacji na jej temat.

=== KARTA KREDYTOWA

Dla *Karty Kredytowej* system prezentuje:

* Informacje:

** *Dostępne środki* – kwota dostępnych środków wraz z walutą, wartość prezentowana tylko dla karty kredytowej głównej,
** *Data ważności* – data ważności karty kredytowej w formacie MM/RRRR,
** *Limit kredytowy* – kwota limitu kredytowego,
** *Ostatnie transakcje* – sekcja dostępna jeżeli na karcie były wykonane operacje kartowe, system prezentuje 3 ostatnie operacje wykonane kartą, wraz z informacją:

*** Data transakcji – data transakcji w formacie DD.MM.RRRR,
*** Opis transakcji – opis transakcji.

* Określony zestaw akcji:

** [HISTORIA KARTY] – umożliwia przeglądnie historii operacji na karcie,
** [ZMIEŃ LIMIT] – umożliwia zmianę limitu karty,
** [WYCIĄGI] – umożliwia przeglądanie listy wyciągów,
** [ZASTRZEŻ] – umożliwia zastrzeżenie karty,
** [SPŁAĆ] – umożliwia spłatę karty,

=== KARTA DEBETOWA

Dla *Karty debetowej* system prezentuje:

* Informacje:

** *Dostępne środki* – kwota dostępnych środków wraz z walutą,
** *Data ważności* – data ważności karty kredytowej (data w formacie MM/RRRR),
** *Ostatnie transakcje* – sekcja dostępna jeżeli na karcie były wykonane operacje kartowe, system prezentuje 3 ostatnie operacje wykonane kartą, wraz z informacją:

*** Data transakcji – data transakcji w formacie DD.MM.RRRR,
*** Opis transakcji – opis transakcji.

* Określony zestaw akcji:

** [HISTORIA KARTY] - umożliwia przeglądnie historii operacji na karcie,
** [ZMIEŃ LIMIT] – umożliwia zmianę limitu karty,
** [ZASTRZEŻ] – umożliwia zastrzeżenie karty,
** [SZCZEGÓŁY] – umożliwia przeglądanie informacji szczegółowych na temat karty.

Ponowne kliknięcie w obszar rozwiniętego wiersza karty powoduje zwinięcie dodatkowych informacji i przycisków prezentowanych dla karty.

== Podgląd szczegółów

=== KARTA KREDYTOWA

Aby przejść do szczegółów wybranej karty kredytowej należy nacisnąć przycisk [SZCZEGÓŁY] na widżecie *Karty,* albo należy kliknąć w obszar wybranego wiersza, a następnie wybrać opcję [SZCZEGÓŁY].

Na formularzu ze szczegółami karty kredytowej głównej/dodatkowej prezentowane są następujące dane:

* *Numer karty* – częściowo zamaskowany numer karty (widoczne 4 pierwsze i 4 ostatnie cyfry numeru karty),
* *Nazwa i typ karty* – nazwa karty nadawana w systemie oraz typ karty: Kredytowa główna, Kredytowa dodatkowa,
* *Nazwa własna* – nazwa karty nadana przez Użytkownika,

Dodatkowo na formularzu prezentowane są rozwijane sekcje:

* [INFORMACJE O SPŁACIE POKAŻ]:
** *Kwota zadłużenia z ostatniego wyciągu* – pole dostępne dla właściciela lub współwłaściciela do umowy kredytowej,
** *Minimalna kwota do spłaty* – pole dostępne dla właściciela lub współwłaściciela do umowy kredytowej,

* [DANE LIMITÓW - POKAŻ]:

** *Dzienny limit wartości operacji gotówkowych* – zdefiniowany limit dzienny dla transakcji gotówkowych,
** *Dzienny limit wartości operacji internetowych* – zdefiniowany limit dzienny dla transakcji internetowych,
** *Dzienny limit wartości operacji bezgotówkowych* – zdefiniowany limit dzienny dla transakcji bezgotówkowych__.__

Pod informacją o limitach (tylko w sytuacji gdy rozwinięta jest sekcja DANE LIMITÓW) dostępna jest akcja:

=== KARTA DEBETOWA

Aby przejść do szczegółów wybranej karty debetowej należy nacisnąć przycisk [SZCZEGÓŁY] na widżecie *Karty,* albo należy kliknąć w obszar wybranego wiersza, a następnie wybrać opcję [SZCZEGÓŁY].

* *Numer karty* – częściowo zamaskowany numer karty (widoczne 4 pierwsze i 4 ostatnie cyfry numeru karty),
* *Nazwa i typ karty* – nazwa karty nadawana w systemie oraz typ karty: Debetowa,
* *Nazwa własna* – nazwa karty nadana przez Użytkownika,

Dodatkowo na formularzu prezentowana jest rozwijana sekcja:

* [DANE LIMITÓW – POKAŻ]:

** *Dzienny limit wartości operacji gotówkowych* – zdefiniowany limit dzienny dla transakcji gotówkowych,
** *Dzienny limit wartości operacji internetowych* – zdefiniowany limit dzienny dla transakcji internetowych,
** *Dzienny limit wartości operacji bezgotówkowych* – zdefiniowany limit dzienny dla transakcji bezgotówkowych__.__

Pod informacją o limitach (tylko w sytuacji gdy rozwinięta jest sekcja DANE LIMITÓW) dostępna jest akcja:

* [ZMIEŃ LIMIT] – umożliwia zmianę limitów karty (zmiana limitów karty została opisana w punkcie _Zmiana limitów karty_).

W górnej części formularza SZCZEGÓŁY KARTY dostępne są przyciski:

*  – umożliwiający przejście do formularza KARTY z listą kart,
* – umożliwiający wyjście do pulpitu.

== Modyfikacja nazwy własnej karty

W celu ułatwienia identyfikacji karty, Użytkownik ma możliwość modyfikacji nazwy produktu z poziomu:

* listy kart za pomocą ikonki znajdującej się przy nazwie karty

* szczegółów karty za pomocą ikonki znajdującej się przy polu *Nazwa własna*.

Obok pola dostępne są przyciski:

* – umożliwia zapisanie zmienionej nazwy własnej karty. Nazwę własną karty zapisać można także po jej wprowadzeniu i użyciu klawisza [Enter] z klawiatury.
* – umożliwia rezygnację ze zmiany nazwy własnej karty.

W przypadku, gdy Użytkownik usunie wprowadzoną w polu nazwę własną karty, system przyporządkowuje mu nazwę systemową.

== Przeglądanie historii operacji wykonanych kartą

Aby przejść do historii operacji wykonanych kartą płatniczą należy kliknąć w obszar wybranego wiersza, a następnie wybrać [HISTORIA KARTY].

Posiadacz głównej karty kredytowej ma możliwość wyświetlenia wszystkich operacji wykonanych kartą płatniczą oraz operacji wykonanych na rachunku związanym z tą kartą.

W celu zawężenia prezentacji listy operacji wykonanych kartą, system umożliwia zastosowanie filtrów:

* *Prostego* – filtrowanie listy kart następuje po wpisaniu danych w polu wyszukiwania znajdującego się nad listą:

System filtruje listę już po wpisaniu pierwszej litery/cyfry/znaku.

* *Zaawansowanego* – użycie przycisku [POKAŻ FILTRY] umożliwia ustawienie filtru zaawansowanego +
Użytkownik ma możliwość ustawiania filtru zaawansowanego dla następujących pól:

** *Ostatnie* – liczba dni poprzedzających datę bieżącą, dla których ma zostać zaprezentowana historia operacji wykonanych kartą płatniczą, domyślnie 30 dni,
** *Zakres dat* - zakres dat, dla których ma zostać wyświetlona historia operacji wykonanych kartą płatniczą, od miesiąca wstecz do daty bieżącej.

** *Nazwa lub tytuł operacji* – możliwość wyszukania po nazwie lub tytule operacji,
** *Kwota od*, *Kwota do* – zakres kwot (od - do), dla których ma zostać wyświetlona historia operacji wykonanych kartą płatniczą,
** *Rodzaj operacji –* Użytkownik mam możliwość filtrowania operacji po rodzaju, poprzez wybór wartości z dostępnej listy:

*** Wszystkie (wartość domyślna),
*** Obciążenia,
*** Uznania, +

** *Status rozliczenia* – Użytkownik mam możliwość filtrowania operacji po statusie, poprzez wybór wartości z dostępnej listy:

*** Wszystkie (wartość domyślna),
*** Rozliczone,
*** Nierozliczone (blokady).

Zastosowanie filtru zaawansowanego aktywuje się za pomocą przycisku [FILTRUJ].

Na formularzu HISTORIA KARTY dostępne są następujące informacje:

* *Data wykonania* – data wykonania operacji (data w formacie DD.MM.RRRR),

== Zmiana limitów karty

Aby zmienić limity karty należy na formularzu SZCZEGÓŁY KARTY, po rozwinięciu opcji [DANE LIMITU – POKAŻ], wybrać przycisk [ZMIEŃ LIMIT], albo należy kliknąć w obszar wybranego wiersza, a następnie wybrać opcję [ZMIEŃ LIMIT].

Na formularzu ZMIANA LIMITU KARTY system prezentuje następujące informacje:

* *Numer karty* – częściowo zamaskowany numer karty (widoczne 4 pierwsze i 4 ostatnie cyfry numeru karty), którego dotyczą prezentowane limity, pole zablokowane do edycji,
* *Dzienny limit wartości operacji gotówkowych*, wraz z następującymi parametrami:

** Kwota dziennego limitu operacji gotówkowych wraz z walutą – system podpowiada obecna kwotę i walutę limitu, pole umożliwia zmianę kwoty limitu,
** Min – minimalna kwota limitu którą Użytkownik może ustawić, pole informacyjne,
** Maks – maksymalna kwota limitu którą Użytkownik może ustawić, pole informacyjne,
** Do maksymalnej wysokości limitu –checkbox, po zaznaczeniu którego system w polu *Dzienny limit wartości operacji gotówkowych* wstawia maksymalną wartość limitu, bez możliwości zmiany (pole zablokowane do edycji),

* *Dzienny limit wartości operacji bezgotówkowych*, wraz z następującymi parametrami:

** Kwota dziennego limitu operacji bezgotówkowych wraz z walutą – system podpowiada obecna kwotę i walutę limitu, pole umożliwia zmianę kwoty limitu,
** Min – minimalna kwota limitu którą Użytkownik może ustawić, pole informacyjne,
** Maks – maksymalna kwota limitu którą Użytkownik może ustawić, pole informacyjne,
** Do maksymalnej wysokości limitu – checkbox, po zaznaczeniu którego system w polu *Dzienny limit wartości operacji bezgotówkowych*, wstawia maksymalną wartość limitu, bez możliwości zmiany (pole zablokowane do edycji),

* *Dzienny limit wartości operacji internetowych*, wraz z następującymi parametrami:

** Kwota dziennego limitu operacji internetowych wraz z walutą – system podpowiada obecna kwotę i walutę limitu, pole umożliwia zmianę kwoty limitu,
** Min – minimalna kwota limitu którą Użytkownik może ustawić, pole informacyjne,
** Maks – maksymalna kwota limitu którą Użytkownik może ustawić, pole informacyjne,
** Do maksymalnej wysokości limitu – checkbox, po zaznaczeniu którego system w polu *Dzienny limit wartości operacji internetowych*, wstawia maksymalną kwotę limitu, bez możliwości zmiany (pole zablokowane do edycji).

W górnej część formularza ZMIANA LIMITU KARTY dostępne są przyciski:

*  – umożliwiający powrót do formularza KARTY z listą kart,

* – umożliwiający przejście do pulpitu.

Na formularzu ZMIANA LIMITU KARTY Użytkownik ma możliwość zmiany wszystkich trzech zaprezentowanych limitów, przez wprowadzenie kwoty albo zaznaczenie checkbox, oddzielnie dla każdego limitu.

== Przeglądanie wyciągów z rachunku karty kredytowej

Aby przeglądnąć listę wyciągów danej karty należy na formularzu KARTY kliknąć w obszar karty, a następnie wybrać opcję [WYCIĄGI].

Lista wyciągów jest stronicowana, Użytkownik ma możliwość przejścia do kolejnych stron za pomocą przycisków nawigacji znajdujących się w dolnej części formularza.

W celu zawężenia prezentacji listy wyciągów, system umożliwia zastosowanie filtra zaawansowanego za pomocą przycisku [POKAŻ FILTRY]:

Użytkownik ma możliwość ustawienia filtru zaawansowanego dla następujących pól:

* *Ostatnie* – liczba dni poprzedzających datę bieżącą, dla których ma zostać zaprezentowana lista wyciągów, domyślnie 30 dni,
* *Zakres dat* – zakres dat, dla których ma zostać wyświetlona lista wyciągów, od miesiąca wstecz do daty bieżącej. Alternatywa dla pola *Ostatnie*. Kliknięcie w obszar pól z datami otwiera okno kalendarza, za pomocą którego można określić zakres dat.

Zastosowanie filtru zaawansowanego aktywuje się za pomocą przycisku [FILTRUJ].

Po kliknięciu w obszar danego wyciągu system rozwija wiersz i pojawia się przycisk [POBIERZ], za pomocą którego Użytkownik ma możliwość pobrania konkretnego wyciągu karty w formacie PDF.

W przypadku braku wyciągów prezentowany jest komunikat: "Brak wyciągów do wyświetlenia".

W górnej część formularza dostępne są przyciski:

*  – umożliwiający powrót do formularza KARTY,
* – umożliwiający przejście do pulpitu.

== Zastrzeżenie karty

Aby zastrzec kartę należy na formularzu KARTY kliknąć w obszar karty, a następnie wybrać opcję [ZASTRZEŻ].

=== KARTA KREDYTOWA

System prezentuje następujący formularz.

Na formularzu ZASTRZEŻENIE KARTY, dla karty kredytowej system prezentuje następujące informacje:

* *Numer karty* – częściowo zamaskowany numer karty (widoczne 4 pierwsze i 4 ostatnie cyfry numeru karty), pole zablokowane do edycji,
* *Nazwa i typ karty* – nazwa karty nadawana w systemie,
* *Numer rachunku kredytowego* – numer rachunku kredytowego, do którego wydano kartę,

W górnej części formularza ZASTRZEŻENIE KARTY dostępne są przyciski:

*  – umożliwiający powrót do formularza KARTY,
* – umożliwiający przejście do pulpitu.

Po poprawnej akceptacji zastrzeżenia karty zostanie zaprezentowany komunikat wraz z przyciskiem [WRÓĆ DO PULPITU] umożliwiającym powrót do pulpitu.

=== KARTA DEBETOWA

System prezentuje następujący formularz.

Na formularzu ZASTRZEŻENIE KARTY dla karty debetowej, system prezentuje następujące informacje:

* *Numer karty* – częściowo zamaskowany numer karty (widoczne 4 pierwsze i 4 ostatnie cyfry numeru karty), pole zablokowane do edycji,
* *Nazwa i typ karty* – nazwa karty nadawana w systemie,
* *Numer rachunku* – numer rachunku, do którego wydano kartę,

W górnej części formularza ZASTRZEŻENIE KARTY dostępne są przyciski:

*  – umożliwiający powrót do formularza KARTY,
* – umożliwiający przejście do pulpitu.

Po poprawnej akceptacji zastrzeżenia karty zostanie zaprezentowany komunikat wraz z przyciskiem [WRÓĆ DO PULPITU] umożliwiającym powrót do pulpitu.

== Spłata karty kredytowej

Aby spłacić zadłużenie na karcie kredytowej należy kliknąć w opcję [SPŁAĆ KARTĘ] na widżecie KARTY, albo na formularzu KARTY kliknąć w obszar karty, a następnie wybrać opcję [SPŁAĆ].

Po wyborze przycisku wyświetlony zostaje formularz SPŁATA KARTY z następującymi danymi:

* *Rachunek karty* – pole wypełnione numerem rachunku karty, pole zablokowane do edycji,
* *Z rachunku* – pole zawierające listę rachunków Użytkownika, należy wskazać rachunek, z którego ma być wykonana spłata zadłużenia na karcie, realizacja spłaty karty możliwa jest z rachunków w walucie PLN lub w walucie rachunku karty. W polu podpowiadany jest rachunek ustawiony przez Użytkownika jako domyślny (w opcji _Ustawienia → Rachunek domyślny_), który można zmienić, pole wymagalne,
* *Data wymaganej spłaty* – pole wypełnione automatycznie przez system datą, do której należy uregulować zadłużenie(data w formacie DD.MM.RRRR), pole zablokowane do edycji,

** Kwota minimalna, wraz z informacją o minimalnej kwocie do spłaty oraz pozostałej minimalnej kwocie do spłaty,
** Kwota dowolna,
** Kwota całkowita, wraz z informacją o kwocie wymagalnej do całkowitej spłaty,
** Zadłużenie za ostatni okres rozliczeniowy, wraz z informacją o kwocie zadłużenia za ostatni okres rozliczeniowy oraz kwocie pozostałej do spłaty zadłużenia za ostatni okres rozliczeniowy.

* *Kwota* – kwota spłaty zadłużenia w walucie rachunku karty (kwota nie może być większa od kwoty całkowitego zadłużenia na karcie). Pole kwota:

** należy uzupełnić ręcznie w przypadku wybrania typu spłaty:

*** Kwota dowolna,

** pole wypełniane automatycznie (bez możliwości zmiany) w przypadku wskazania typu spłaty:

*** Kwota minimalna,
*** Kwota całkowita,
*** Zadłużenie za ostatni okres rozliczeniowy,

* *Tytułem* – pole zawiera opis operacji i zaszyfrowany numer karty, pole zablokowane do edycji, informacja jaką system zaprezentuje w tym polu, jest uzależniony od wybranego przez Użytkownika typu spłaty:

** Minimalna kwota – Spłata minimalnego zadł.

* *Data realizacji* – data spłaty zadłużenia (data w formacie DD.MM.RRRR), domyślnie wstawiana jest data bieżąca, pole zablokowane do edycji.

W górnej część formularza SPŁATA KARTY dostępne są przyciski:

*  umożliwiający powrót do formularza KARTY.
* – umożliwiający przejście do pulpitu.

== Aktywacja karty

Aby aktywować kartę należy na formularzu KARTY kliknąć w obszar karty nieaktywnej o statusie _Do akceptacji_, a następnie wybrać opcję [AKTYWUJ].

Po wyborze przycisku wyświetlony zostaje formularz AKTYWACJA KARTY z następującymi danymi (w zależności od typu karty):

* *Numer karty* – częściowo zamaskowany numer karty (widoczne 4 pierwsze i 4 ostatnie cyfry numeru karty), pole zablokowane do edycji,
* *Nazwa i typ karty* – nazwa karty nadawana w systemie oraz typ karty,
* *Numer rachunku kredytowego* – numer rachunku kredytowego, do którego wydano kartę,

W górnej części formularza AKTYWACJA KARTY dostępne są przyciski:

*  – umożliwiający powrót do formularza KARTY,

* – umożliwiający przejście do pulpitu.

Po poprawnej akceptacji aktywacji karty, za pomocą przycisku [AKTYWUJ] zostanie zaprezentowany komunikat jak na poniższym ekranie wraz z przyciskiem [WRÓĆ DO PULPITU] umożliwiającym powrót do pulpitu.

= Karty (GryfCard)

Miniaplikacja Karty zapewnia dostęp do listy kart (debetowych, kredytowych), do których uprawniony jest Użytkownik.

System Asseco EBP zapewnia Użytkownikowi dostęp do miniaplikacji Karty z dwóch głównych poziomów:

* widżetu Karty (wyświetlanego na pulpicie o ile Użytkownik nie usunął go z pulpitu),

* menu bocznego po wybraniu opcji Karty.

W każdym z poziomów miniaplikacji dla Użytkownika dostępne są formatki do obsługi poszczególnych opcji biznesowych opisanych w poniższych podrozdziałach.

Użytkownik posiadający dostęp do miniaplikacji Karty ma możliwość:

* przeglądania informacji listy swoich kart lub wszystkich kart danego rachunku,
* przeglądania informacji szczegółowych na temat karty,
* modyfikacji nazwy własnej karty,

NOTE: Funkcjonalność kart w kontekście firmowym dostępna jest dla Użytkownika, który posiada odpowiednie uprawnienia: do funkcjonalności. Uprawnienia ustawiane są przez Administratora Użytkowników w opcji _Ustawienia → Uprawnienia Użytkowników._

W przypadku braku łączności systemu bankowości internetowej _Asseco_EBP_ z systemem kartowym zostanie zaprezentowany komunikat:

== Widżet karty

Widżet *Karty* może być w dwóch rozmiarach: standardowym i rozszerzonym.

Na widżecie standardowym jest możliwość:

* wyboru karty w celu zaprezentowaniu skróconych informacji o niej, czyli:
** numer karty częściowo zamaskowany,
** dane właściciela,
** data ważności,
** rodzaj karty,
** limit kredytu.
* [SPŁAĆ KARTĘ] - przejście do spłaty karty (przycisk dostępny w zależności od rodzaju karty),,
* [SZCZEGOŁY] - przejście do szczegółów wybranej karty.

Na widżecie rozszerzonym prócz tych samych informacji co na widoku standardowym dodatkowo prezentowane są:

* informacja o ostatniej transakcji na karcie:
** kwota,
** tytuł,
** data,
(w przypadku braku ostatnich transakcji wyświetli się odpowiedni komunikat).

== Przeglądanie listy kart

Po kliknięciu w tytuł widżetu *Karty* lub poprzez wybór opcji z bocznego menu Karty wyświetlane jest okno prezentujące listę kart, do których uprawniony jest Użytkownik:

Na liście kart, dla każdej karty dostępne są następujące informacje:

* *Nazwa i numer* - nazwa karty (nadana przez system), numer karty częściowo zamaskowany,

* *Rodzaj karty* - rodzaj karty (debetowa, kredytowa),

* *Właściciel* - imię i nazwisko właściciela karty,

* *Aktywność* - dostępne statusy _Aktywna, Nieaktywna,_

* *Status* - status karty, dostępne statusy: _Ważna, Nieważna, Zablokowana, Zastrzeżona, Do aktywacji._ Wartość
prezentowana jako status zależy od:

** daty zastrzeżenia: jeśli data zastrzeżenia jest przed datą aktualną - prezentowany jest status _Zastrzeżona,_

** daty zablokowania: jeśli data zablokowania jest przed datą aktualną - prezentowany jest status _Zablokowana,_

** daty ważności: jeśli data końca ważności jest przed datą aktualną - prezentowany jest status _Nieważna._

Jeśli powyższe warunki nie są spełnione - karta posiada status _Ważna (Aktywna/Nieaktywna)._
System umożliwia także filtrowanie listy kart po wybraniu ikony znajdującej się nad listą, a następnie po wpisaniu danych w polu wyszukiwania:

System filtruje listę już po wpisaniu pierwszej litery/cyfry/znaku.

Dodatkowo Użytkownik mam możliwość filtrowania kart po statusie karty poprzez wybór wartości z dostępnej listy: _Wszystkie, Ważna (wartość domyślna) , Nieważna, Zablokowana, Zastrzeżona, Do aktywacji._

== Akcje na wybranej karcie

Kliknięcie w wiersz wybranej karty powoduje wyświetlenie dodatkowych informacji na temat karty:

* *Kwota dostępnego limitu* - wykorzystany limit na karcie, wartość prezentowana tylko dla karty kredytowej głównej,
* *Data ważności* - data ważności karty kredytowej w formacie MM/RRRR,
* *Płatności zbliżeniowe* - czy kartą możliwe są płatności zbliżeniowe,

Dodatkowo prezentowany jest określony zestaw akcji:

* [HISTORIA KARTY] - umożliwia przeglądnie historii operacji na karcie,
* [ZMIEŃ LIMITY] - umożliwia zmianę limitów na karcie,
* [LISTA BLOKAD] - prezentowana jest lista blokad na karcie,

Ponowne kliknięcie w obszar rozwiniętego wiersza karty powoduje zwinięcie dodatkowych informacji i przycisków prezentowanych dla karty.

== Podgląd szczegółów karty

Aby z listy kart przejść do szczegółów wybranej karty należy kliknąć w obszar wybranego wiersza, a następnie opcję [SZCZEGÓŁY].

Na formatce ze szczegółami karty kredytowej głównej/dodatkowej prezentowane są następujące dane:

* *Numer karty* - częściowo zamaskowany numer karty,
* *Nazwa i typ karty* - nazwa karty nadawana w systemie oraz typ karty: Kredytowa główna, Kredytowa dodatkowa,
* *Nazwa własna* - nazwa karty nadana przez Użytkownika,

* *Limit kredytowy* - kwota i waluta przyznanego limitu kredytowego, pole dostępne dla właściciela lub współwłaściciela do umowy kredytowej,

* [DANE LIMITÓW - POKAŻ]

== Modyfikacja nazwy własnej karty

W celu ułatwienia identyfikacji karty, Użytkownik z poziomu szczegółów karty ma możliwość modyfikacji nazwy produktu za pomocą ikonki znajdującej się przy polu *Twoja nazwa.*

Wybranie ikonki w polu uaktywnia pole do wprowadzenia nazwy własnej karty:

Obok pola dostępne są przyciski:

* – umożliwia zapisanie zmienionej nazwy własnej karty. Nazwę własną karty zapisać można także po jej wprowadzeniu i użyciu klawisza [Enter] z klawiatury.
* – umożliwia rezygnację ze zmiany nazwy własnej karty.

W przypadku, gdy Użytkownik usunie wprowadzoną w polu nazwę własną karty, system przyporządkowuje mu nazwę systemową.

== Przeglądanie historii operacji wykonanych kartą

Aby przejść do historii operacji wykonanych kartą płatniczą należy z poziomu rozwiniętych szczegółów karty (na liście karty) wybrać przycisk [HISTORIA KARTY].

Posiadacz głównej karty kredytowej ma możliwość wyświetlenia wszystkich operacji wykonanych kartą płatniczą oraz operacji wykonanych na rachunku związanym z tą kartą.

W celu zawężenia prezentacji listy operacji wykonanych kartą, Użytkownik ma możliwość zastosowania filtrów: prostego oraz zawansowanego.

Filtr prosty umożliwia wyszukanie po treści.

Użycie przycisku [POKAŻ FILTRY] umożliwia ustawienie filtru zaawansowanego dla następujących pól:

* *Ostatnie … dni* - liczba dni poprzedzających datę bieżącą, dla których ma zostać zaprezentowana historia
operacji wykonanych kartą płatniczą, domyślnie 30 dni,
* *Zakres dat* - zakres dat,  klikniecie w obszar pól z datami otwiera okno kalendarza, za pomocą, którego można określić zakres dat (maksymalnie 90 dni wstecz),
* *Nazwa lub tytuł operacji* - możliwość wyszukania nazwy lub tytułu operacji,
* *Zakres operacji* - filtr dostępny dla historii operacji karty kredytowej. Możliwość wyboru:
** _Wszystkie operacje,_
** _Tylko operacje wykonywane kartą._
* *Kwota od, Kwota do* - zakres kwot (od - do), dla których ma zostać wyświetlona historia operacji wykonanych kartą płatniczą.

Zastosowanie filtru zaawansowanego aktywuje się za pomocą przycisku [FILTRUJ].

== Przeglądanie blokad na rachunku karty

Aby z listy kart przejść do przeglądania aktywnych operacji zablokowania środków należy kliknąć w obszar wybranego wiersza karty, a następnie opcję [LISTA BLOKAD].

System umożliwia filtrowanie listy blokad po wpisaniu danych w polu wyszukiwania:

System filtruje listę już po wpisaniu pierwszej litery/cyfry/znaku.

== Spłata karty

Po wybraniu przycisku [SPŁAĆ] Użytkownik zostanie przekierowany do strony z danymi do spłaty:

Po uzupełnieniu danych i wybraniu [SPŁAĆ] nastąpi przejście do kroku z podsumowaniem i autoryzacją transakcji.

= Wniosek o kartę debetową (CardOn)

Na liście *Wniosków* (aplikacja Karty -> Wnioski) prezentowane są wnioski wprowadzone przez
klienta w swoim imieniu lub dla osób trzecich.

Wniosek po poprawnym złożeniu przyjmuje status "Nowy", a po przyjęciu przez system zewnętrzny
(CardOn) zmienia status na "Wysłany do analizy".

Wniosek po pozytywnym rozpatrzeniu zmienia status na "Zatwierdzony przez Bank".

Wniosek o kartę w statusie "Przekazany do produkcji" jest ostatecznym statusem wniosku.

Wniosek w statusie "Odrzucony" - status ostateczny, wniosek został odrzucony
Klient może złożyć nowy wniosek o kartę.

== Nowy wniosek o kartę debetową (CardOn)

NOTE: Możliwość zamawiania kart przez użytkownika jest chroniona uprawnieniem
funkcjonalnym "Wniosek o kartę" z zakresu Kart.

Użytkownik z uprawnieniem "Wniosek o kartę" ma możliwość zamawiania kart
dla siebie i innych użytkowników firmy.

W aplikacji "Karty" po wybraniu "Zamów kartę":

zostaje otwarte okno wyboru karty:

Po wskazaniu opcji "Karta debetowa" następuje przejście do formularza wniosku o kartę debetową.

*_Wybór rachunku i właściciela karty_*

W pierwszym kroku klient wskazuje rachunek, do którego chciałby zamówić kartę debetową.

W kontekście firmowym (obszar roboczy korporacyjny) wniosek o "Kartę debetową"
może zostać złożony w imieniu własnym lub w imieniu osoby uprawnionej
do rachunku.

Lista potencjalnych właścicieli karty tworzona jest w oparciu o wszystkich
klientów posiadających relację z danym rachunkiem, których dane są dostępne
w bankowości internetowej.

Na liście prezentowani są wszyscy użytkownicy z danego kontekstu:

Nazwa na karcie prezentuje nazwę firmy, która będzie widoczna na kacie firmowej.

*_Potwierdzenie danych osobowych_*

W kontekście firmowym wniosek o "Kartę debetową" może zostać złożony
w imieniu własnym lub w imieniu osoby uprawnionej do rachunku.

W przypadku składania wniosku dla siebie użytkownikowi prezentowane są jego zamaskowane
dane osobowe, a sam użytkownik proszony jest o potwierdzenie ich zgodności ze

== Nowy wniosek o kartę kredytową (CardOn)

W aplikacji _Karty_ po wybraniu _Zamów kartę_:

zostaje otwarte okno wyboru karty:

Po wskazaniu opcji *Karta kredytowa* następuje przejście do formularza wniosku
o kartę kredytową.

"Wniosek dotyczy wydania pierwszej
karty kredytowej.

*Wnioskowana kwota limitu*

Następnie użytkownik otrzymuje informację o widełkach dla kwoty limitu kredytowego,
które są sumą logiczną limitów dla wszystkich kart kredytowych dostępnych dla klienta
tego typu.

*Właścicielem karty* jest osoba składająca wniosek o kartę kredytową lub
wybrany reprezentant firmy.

*Nazwa na karcie* prezentuje nazwę firmy, która będzie widoczna na kacie firmowej.

*Potwierdzenie danych*

W przypadku składania wniosku dla siebie użytkownikowi prezentowane są jego
zamaskowane dane osobowe, a sam użytkownik proszony jest o potwierdzenie
ich zgodności ze stanem faktycznym.

Wymagane jest potwierdzenie danych osobowych i firmowych:

Przed kontynuowaniem składania wniosku system dokonuje weryfikacji wymaganych danych.

NOTE: Aby w aplikacji Ustawienia możliwy był podgląd i edycja danych osobowych konieczne jest
włączenie usługi: userPersonalDataChangeEnabled , userPersonalDataAccessAuthorize oraz
userPersonalDataInCorpoChange.

= Karty (Visiona - GAPI)

== Aktywacja karty

Po otrzymaniu karty Klient może aktywować kartę poprzez wybranie opcji [Aktywuj]:

* z poziomu listy Kart w wierszu karty o statusie _Wyprodukowana_:

* lub na formularzu szczegółów karty:

Po wyborze opcji [Aktywuj] wyświetlony zostaje formularz z następującymi danymi
(w zależności od typu karty):

Formularz aktywacji karty debetowej:

Użytkownik powinien podać datę ważności (w formacie MM/RR) karty odczytaną z
fizycznej karty i wybrać [Akceptuj]

Dane formularza:

* *Numer karty* – częściowo zamaskowany numer karty (widoczne 4 pierwsze
i 4 ostatnie cyfry numeru karty),
* *Nazwa i typ karty* – typ karty: Kredytowa, Debetowa,
* *Numer rachunku powiązanego z kartą* - dla karty debetowej to numer rachunku,
do którego wydano kartę,
* *Imię i nazwisko okaziciela* – imię i nazwisko właściciela karty,
* *Imię i nazwisko na karcie* – imię i nazwisko umieszczone na karcie.

Podpisać przypisanym środkiem autoryzacji:

Po poprawnej akceptacji zostanie zaprezentowane potwierdzenie:

== Zmiana limitów karty

Zmiana limitów karty jest możliwa z poziomu:

* Listy kart - wybór opcji "Zmień limity":

* Szczegółów karty po wybraniu "Dane limitów - pokaż":

prezentowana jest wartość limitów karty z możliwością ich zmiany "Zmień limity"

Formularz "Zmiany limitów karty":

Użytkownik ma możliwość zmiany limitów, przez wprowadzenie wartości kwoty albo
zaznaczenie pola wyboru przy każdym z limitów.

Dane formularza:

* *Numer karty* – częściowo zamaskowany numer karty (widoczne 4 pierwsze i
4 ostatnie cyfry numeru karty),
* *Dzienny limit wartości operacji gotówkowych*, wraz z następującymi parametrami:

** Kwota dziennego limitu operacji gotówkowych wraz z walutą – system podpowiada obecną
kwotę i walutę limitu, pole umożliwia zmianę kwoty limitu,
** Min – minimalna kwota limitu, którą Użytkownik może ustawić, pole informacyjne,
** Maks – maksymalna kwota limitu, którą Użytkownik może ustawić, pole informacyjne,
** Do maksymalnej wysokości limitu – pole wyboru, po zaznaczeniu którego system
w polu *Dzienny limit wartości operacji gotówkowych* wstawia maksymalną
wartość limitu, bez możliwości zmiany (pole zablokowane do edycji),

* *Dzienny limit wartości operacji bezgotówkowych*, wraz z następującymi parametrami:

** Kwota dziennego limitu operacji bezgotówkowych wraz z walutą – system podpowiada
obecną kwotę i walutę limitu, pole umożliwia zmianę kwoty limitu,
** Min – minimalna kwota limitu, którą Użytkownik może ustawić, pole informacyjne,

== Zablokowanie (czasowe karty)

Zablokowanie (czasowe) karty jest możliwe z poziomu listy kart:

Wybranie opcji [Zablokuj] (czasowo) otwiera formularz,
na którym Klient podpisuje dyspozycję zablokowania (czasowego)
karty przypisanym środkiem autoryzacji::

Po poprawnej akceptacji zostaje zaprezentowany komunikat potwierdzający:

== Odblokowanie karty (czasowo zablokowanej)

Odblokowanie karty (czasowo zablokowanej) jest możliwe z poziomu listy kart:

Wybranie opcji [Odblokuj] otwiera formularz,
na którym Klient podpisuje dyspozycję odblokowania karty przypisanym
środkiem autoryzacji::

Po poprawnej akceptacji zostaje zaprezentowany komunikat potwierdzający:

== Zastrzeżenie karty (na stałe)

Zastrzeżenie karty (na stałe) jest możliwe z poziomu listy kart:

Wybranie opcji [Zastrzeż] (na stałe) otwiera formularz:

Należy wskazać przyczynę zastrzegania karty:

* Karta została zgubiona
* Karta zostałą skradziona
* Inny powód z polem tekstowym, gdzie należy opisać przyczynę zastrzegania:

Po wskazaniu ww. powodów prezentowany jest komunikat informacyjny:

"Czy na pewno chcesz zastrzec kartę?

* *Karta uległa zniszczeniu*

Po wskazaniu powodu "Karta uległa zniszczeniu" prezentowany jest komunikat informacyjny:

"Ta karta będzie działać do czasu, gdy otrzymasz nową kartę i ją aktywujesz.

Na liście kart w przypadku zniszczenia karty prezentowane są dwa rekordy karty.

Proces zastrzeżenia karty wymaga akceptacji i podpisu przypisanym środkiem
autoryzacji:

Po poprawnej akceptacji zostaje zaprezentowany komunikat potwierdzający:

== Aktywacja wznawianej karty

Po zastrzeżeniu karty z powodu "Karta uległa zniszczeniu" do klienta zostanie wysłana
nowa karta.

Na liście kart (w przypadku zniszczenia karty) prezentowane są dwa rekordy karta zastrzeżona w statusie _Aktywna_
i karta nowa wznawiana w statusie _Wyprodukowana (wznawiana)_.

Po otrzymaniu karty klient może ją aktywować z poziomu listy kart:

Po wybraniu [Aktywuj] zostaje wyświetlony formularz:

Proces aktywacji wznawianej karty przebiega tak samo jak proces aktywacji nowej karty.

Złożenie dyspozycji aktywacji karty wymaga podpisu przypisanym środkiem autoryzacji:

Poprawna akceptacja zostanie potwierdzona komunikatem:

Transakcje nową kartą (wznowioną) można potwierdzać tym samym PIN-em
co kartą zniszczoną.

= Przeglądanie historii operacji wykonanych kartą

Aby przejść do historii operacji wykonanych kartą płatniczą należy kliknąć w obszar wybranego wiersza, a następnie wybrać [HISTORIA KARTY].

Posiadacz głównej karty kredytowej ma możliwość wyświetlenia wszystkich operacji wykonanych kartą płatniczą oraz operacji wykonanych na rachunku związanym z tą kartą.

W celu zawężenia prezentacji listy operacji wykonanych kartą, system umożliwia zastosowanie filtrów:

* *Prostego* – filtrowanie listy kart następuje po wpisaniu danych w polu wyszukiwania znajdującego się nad listą:

System filtruje listę już po wpisaniu pierwszej litery/cyfry/znaku.

* *Zaawansowanego* – użycie przycisku [POKAŻ FILTRY] umożliwia ustawienie filtru zaawansowanego +
Użytkownik ma możliwość ustawiania filtru zaawansowanego dla następujących pól:

** *Ostatnie* – liczba dni poprzedzających datę bieżącą, dla których ma zostać zaprezentowana historia operacji wykonanych kartą płatniczą, domyślnie 30 dni,
** *Zakres dat* - zakres dat, dla których ma zostać wyświetlona historia operacji wykonanych kartą płatniczą, od miesiąca wstecz do daty bieżącej.

** *Nazwa lub tytuł operacji* – możliwość wyszukania po nazwie lub tytule operacji,
** *Kwota od*, *Kwota do* – zakres kwot (od - do), dla których ma zostać wyświetlona historia operacji wykonanych kartą płatniczą,
** *Rodzaj operacji –* Użytkownik mam możliwość filtrowania operacji po rodzaju, poprzez wybór wartości z dostępnej listy:

*** Wszystkie (wartość domyślna),
*** Obciążenia,
*** Uznania, +

** *Status rozliczenia* – Użytkownik mam możliwość filtrowania operacji po statusie, poprzez wybór wartości z dostępnej listy:

*** Wszystkie (wartość domyślna),
*** Rozliczone,
*** Nierozliczone (blokady).

Zastosowanie filtru zaawansowanego aktywuje się za pomocą przycisku [FILTRUJ].

Na formularzu HISTORIA KARTY dostępne są następujące informacje:

* *Data wykonania* – data wykonania operacji (data w formacie DD.MM.RRRR),
* *Data księgowania* – data księgowania operacji (data w formacie DD.MM.RRRR),
* *Opis operacji* – opis operacji,

W górnej część formularza HISTORIA KARTY dostępne są przyciski:

*  – umożliwiający powrót do formularza KARTY z listą kart,

* – umożliwiający przejście do pulpitu.

W dolnej część formularza HISTORIA KARTY prezentowane jest Podsumowanie strony z z uwzględnieniem podziału na wpływy i wydatki oraz liczby operacji.

