:imagesdir: images

= Rachunki powiernicze

Miniaplikacja *Rachunki powiernicze* zapewnia dostęp do podglądu mieszkaniowego rachunku powierniczego (MRP) wraz z rachunkami ewidencyjnymi w trybie pasywnym.

System Asseco EBP zapewnia Użytkownikowi dostęp do miniaplikacji *Rachunki powiernicze* z dwóch głównych poziomów:

* widżetu *Rachunki MRP* (wyświetlanego na pulpicie o ile Użytkownik nie usunął go z pulpitu),

* menu bocznego po wybraniu opcji _Rachunki powiernicze_.

W każdym z poziomów miniaplikacji dla Użytkownika dostępne są formatki do obsługi poszczególnych opcji biznesowych opisanych w poniższych podrozdziałach.

Użytkownik posiadający dostęp do miniaplikacji *Rachunki powiernicze* ma możliwość:

* przeglądania skróconych informacji o rachunkach MRP na widżecie miniaplikacji *Rachunki powiernicze*,
* przeglądania rachunków powierniczych,

NOTE: Funkcjonalność rachunki powiernicze dostępna jest dla Użytkownika, który posiada odpowiednie uprawnienia: do funkcjonalności i do rachunków. Uprawnienia ustawiane są przez Administratora Użytkowników w opcji _Ustawienia → Uprawnienia Użytkowników_.

== Widżet Rachunki MRP

Widżet *Rachunki MRP* jest prezentowany w rozmiarze: standardowym.

* ikona 

Na widżecie standardowym prezentowane są informacje:

* *Rodzaj rachunku* – rodzaj rachunku,
* *NRB* – numer rachunku,

Na dole widżetu dostępna jest akcja:

* [POKAŻ WSZYSTKIE] - przejście do listy rachunków.

== Przeglądanie listy rachunków

Po kliknięciu w tytuł widżetu *Rachunki MPR* lub poprzez wybór opcji z bocznego menu _Rachunki powiernicze_ wyświetlane jest okno prezentujące listę rachunków, do których dany Użytkownik jest uprawniony.

Domyślnie na liście wyświetlane są rachunki aktywne.

Rachunki sortowane są w pierwszej kolejności wg daty otwarcia.

System umożliwia filtrowanie listy rachunków po wybraniu odpowiedniej wartości w polu _Wyszukaj:_
System filtruje listę już po wpisaniu pierwszej litery/cyfry/znaku.

Na liście rachunków dla każdego rachunku dostępne są następujące informacje:

* *Rachunek powierniczy* – typ rachunku wraz z nazwą i numerem rachunku,
* *Saldo księgowe* – saldo rachunku,

Pod każdym rachunkiem dostępne są następujące opcje:

* [RACHUNKI EWIDENCYJNE] – naciśniecie powoduje przekierowanie Użytkownika na formularz Rachunki ewidencyjne, umożliwiający przeglądanie(operacji na rachunkach ewidencyjnych, zestawienie składek DFG, generowanie wyciągu Raport wpłat),
* [OPERACJE NA RACH. MPR] -naciśniecie powoduje przekierowanie Użytkownika na formularz Historia rachunku, eksport listy do pliku PDF lub do zdefiniowanego w [Ustawienia importu i eksportu]

Pod listą rachunków dostępne jest:

* *Podsumowanie strony* – zawierające łączną (dla wszystkich rachunków) saldo księgowe, dostępne środki,

* *Przyciski nawigacji* – przy pomocy których Użytkownik ma możliwość poruszania się pomiędzy poszczególnymi stronami z listą rachunków.

== Akcje na wybranym rachunku powierniczym

Kliknięcie w wiersz wybranego rachunku powoduje wyświetlenie dodatkowych informacji na temat rachunku.

System prezentuje:

* [RACHUNKI EWIDENCYJNE] – naciśniecie powoduje przekierowanie Użytkownika na formularz Rachunki ewidencyjne, umożliwiający przeglądanie(operacji na rachunkach ewidencyjnych, zestawienie składek DFG, generowanie wyciągu Raport wpłat),
* [OPERACJE NA RACH. MPR] -naciśniecie powoduje przekierowanie Użytkownika na formularz Historia rachunku, eksport listy do pliku PDF lub do zdefiniowanego w [Ustawienia importu i eksportu]

Ponowne kliknięcie w obszar rozwiniętego wiersza rachunku powoduje zwinięcie dodatkowych informacji i przycisków prezentowanych dla rachunku.

== Modyfikacja nazwy własnej rachunku

W celu ułatwienia identyfikacji rachunków, Użytkownik ma możliwość modyfikacji nazwy produktu z poziomu:

* szczegółów lokaty za pomocą ikonki  znajdującej się przy polu _Nazwa własna_.

W celu ułatwienia identyfikacji rachunku, Użytkownik z poziomu szczegółów rachunku ma możliwość ustawienia nazwy własnej dla rachunku za pomocą ikony znajdującej się obok pola _Twoja nazwa_.

W przypadku, gdy Użytkownik usunie wprowadzoną w polu nazwę własną rachunku, system przyporządkowuje mu nazwę systemową.

Nazwa własna przypisana jest do Użytkownika, co oznacza, że ten sam produkt u różnych Użytkowników może posiadać różną nazwę.

Obok pola dostępne są przyciski:

*  – umożliwia zapisanie nazwy własnej rachunku. Nazwę własną rachunku można zapisać również po jej wprowadzeniu i użyciu klawisza [Enter] z klawiatury.
*  – umożliwia rezygnację z ustawienia nazwy własnej rachunku.

W przypadku, gdy Użytkownik usunie wprowadzoną w polu nazwę własną rachunku, system przyporządkowuje mu nazwę systemową z pola _Typ rachunku_.

Nazwa własna przypisana jest do Użytkownika co oznacza, że ten sam produkt u różnych Użytkowników może posiadać różną nazwę.

== Przeglądanie szczegółów rachunku

Aby z listy rachunków przejść do szczegółów wybranego rachunku należy kliknąć w obszar wybranego wiersza i wybrać przycisk [SZCZEGÓŁY].

Na formularzu prezentowane są następujące dane:

* *Numer rachunku* – numer rachunku w formacie NRB,
* *Waluta* – symbol waluty w jakiej prowadzony jest rachunek,

Obok szczegółów rachunku dostępne są:

* Opcje:

** [RACHUNKI EWIDENCYJNE] – umożliwiająca przeglądanie rachunków ewidencyjnych,
** [OPERACJE NA RACH.

* Przyciski:

**  – umożliwiający powrót do formularza RACHUNKI POWIERNICZE,

**  – umożliwiający wyjście do pulpitu.

== Rachunki ewidencyjne

Wybranie przycisku [RACHUNKI EWIDENCYJNE] dostępnego po rozwinięciu szczegółów rachunku, umożliwia Użytkownikowi podgląd rachunków ewidencyjnych powiązany z MRP i RS_DFG grupujący operacje na tych umowach w odniesieniu do nabywcy.

Użytkownik ma możliwość wykonania operacji dla wszystkich rachunków lub dla wybranego:

Opcje dla wszystkich rachunków ewidencyjnych:

** [OPERACJE ZBIORCZE] – umożliwiająca przeglądanie operacji na rachunkach ewidencyjnych,
** [SKŁADKI DFG ZBIORCZE] – umożliwiająca przeglądanie składek DFG,
** [WYCIĄG ZBIORCZY] – umożliwiająca generowanie wyciągu operacji na rachunkach ewidencyjnych.

Opcje dla pojedynczego rachunku ewidencyjnego:

** [OPERACJE] – umożliwiająca przeglądanie operacji na rachunku ewidencyjnych,
** [SKŁADKI DFG] – umożliwiająca przeglądanie składek DFG,
** [WYCIĄG] – umożliwiająca generowanie wyciągu operacji na rachunku ewidencyjnym.

=== Szczegóły rachunku ewidencyjnego

Aby przejść do szczegółów wybranego rachunku ewidencyjnego należy kliknąć w przycisk [SZCZEGÓŁY].

Na formularzu prezentowane są następujące dane:

* *Numer rachunku ewidencyjnego* – numer rachunku w formacie NRB,
* *Waluta* – symbol waluty w jakiej prowadzony jest rachunek,

Obok szczegółów rachunku dostępne są:

* Opcje:

** [OPERACJE] – umożliwiająca przeglądanie operacji na rachunku ewidencyjnych,
** [SKŁADKI DFG] – umożliwiająca przeglądanie składek DFG,
** [WYCIĄG] – umożliwiająca generowanie wyciągu operacji na rachunku ewidencyjnym.

== Składki do opłacenia

W celu wykonania operacji opłacenia składki do rachunku powierniczego należy kliknąć w obszar wybranego wiersza rachunku, wybrać przycisk [SKŁADKI DO OPŁACENIA].

Na formularzu prezentowane są następujące dane:

* *Rachunek MRP* – numer rachunku w formacie NRB,
* *Rachunek do obciążenia* – numer rachunku do obciążenia,

Na formularzu SKŁADKI DO OPŁACENIA dostępne są:

* Przyciski:

**  – umożliwiający przejście do formularza RACHUNKI POWIERNICZE,
** – umożliwiający wyjście do pulpitu.

* Akcja:

** [OPŁAĆ] – umożliwia przejście do kroku przelewu, autoryzacji opłaty do rachunku.

Po wybraniu opcji [OPŁAĆ], Użytkownik przekierowany jest do formularza PRZELEWU.

